### ISSUE TITLE
[BUG] Position fixed doesn't work within AnimatePresence

### ISSUE THREAD

**Issue by vavra7** [framer/motion#1117]
Hi all, I am building website with framer motion but run into this issue and don't know how to get over it. It seems that everything that is within AnimatePresence tag and has position fixed is broken.

This is especially problem when you have animated routes, because it means that anything in routes tree can not have position fixed.

Here is an example on codesandbox:
https://codesandbox.io/s/framer-motion-position-fixed-bug-4nqiq?file=/src/App.js:192-207

I can imagine workaround with using react portal, but that won't work with AnimateSharedLayout for instance. Anyway position fixed is important and needs to be working.

**Comment by mattgperry** [comment]
I’ll take a deeper look but first reaction is have you checked this works without AnimatePresence? Because it doesn’t render any DOM or affect any styles.

**Comment by vavra7** [comment]
Ok you are right. I just played with the code little bit and it seems that modal window doesn't behave as fixed element even though I removed AnimatePresence. It means that cause of the problem is not AnimatePresence but propably 'in' animation. I have updated codesandbox example so you can take a look.

**Comment by br79** [comment]
@vavra7 I don't think this is a bug.

For how a [fixed positioned](https://developer.mozilla.org/en-US/docs/Web/CSS/position) element work:

> It is positioned relative to the initial containing block established by the viewport, except when one of its ancestors has a transform, perspective, or filter property set to something other than none, in which case that ancestor behaves as the containing block.

The animated component you created has a style of `transform: translateY(0%)`, so the inner modal window is relative to this animated component but not the viewport.

Maybe you could put the modal window as a sibling to the animated component.

**Comment by vavra7** [comment]
> @vavra7 I don't think this is a bug.
>
> For how a fixed positioned element work:
> > It is positioned relative to the initial containing block established by the viewport, except when one of its ancestors has a transform, perspective, or filter property set to something other than none, in which case that ancestor behaves as the containing block.
>
> The animated component you created has a style of transform: translateY(0%), so the inner modal window is relative to this animated component but not the viewport.

@br79 based on you answer I searched a bit and you are right. It seems that motion leaves `transform: translateY(0%) translateZ(0px);` on animated element and so position fixed can not work on any ascendant. I found similar issue on stackoverflow [here](https://stackoverflow.com/questions/15194313/transform3d-not-working-with-position-fixed-children) also saying there is no work-around for that.

> Maybe you could put the modal window as a sibling to the animated component.

I use dynamic imports to utilize webpack code splitting based on the routes (every route has its own bundle and it is downloaded by browser only when needed) and motion is used for animating whole routes. I can not put modal window belonging to route as route sibling without breaking this optimization.

Nevertheless if someone uses animating routes as me it bans him from using position fixed at whole route at all.

**Could be acceptable solution that motion cleans up after itself and wont leave style transform on any element in case of zero values?**

**Comment by mattgperry** [comment]
In 5 transform is set back to `none`, this was indeed a bug

**Comment by ryanfarhan00** [comment]
it seems it's still broken, my fixed navbar get affected by other element animation, even though both are in different parent

**Comment by Jbmanllr** [comment]
This is still an issue although every case is considered closed, it is not.

**Comment by saadiahmadx** [comment]
This is still an issue for me as well.

**Comment by mhamendes** [comment]
The fact that motion leaves `transform: translateY(0%) translateZ(0px);` is breaking the fixed component that works as a page transition. Setting `transform: none;` on transitionEnd prop fixes the page design breaking, but breaks the page exit transition.

**Comment by UF-code** [comment]
its really funny to see there is indeed a problem but no one comes with real solution instead of the solution just slash to closed tag by the author the question comes to my mind what is the point of the usage of this library atleast you should provide some kinda work around, but no just splash the close tag on it, no mate is not solved and the exercise is you provide is broken just you are saving the day as it seems

**Comment by bhappen** [comment]
> it seems it's still broken, my fixed navbar get affected by other element animation, even though both are in different parent

I'm having this same issue. My fixed navbar component inside my layout is being effected by an opacity animation being used in a different page. This page has a `motion.div` that uses `initial={{ opacity: 0 }} animate={{ opacity: 1 }}`. Strange though that my pages `motion.div` does it's animation for the full duration before the fixed header does it's newly found animation.

Removing the fixed property no longer causes this doubled animation.

**Comment by YakomazovPavel** [comment]
In my case, the following helped me (see using "transitionEnd"): 
`const fooVariants = {
  hidden: {
    x: "-100%",
    opacity: 0,
    transition: {
      type: "linear",
      duration: 0.2
    }
  },
  visible: {
    x: 0,
    opacity: 1,
    transition: {
      type: "linear",
      duration: 0.2
    },
    transitionEnd: {  
      x: 0,
      y: 0,
      z: 0
    },
  },
  exit: {
    x: "-100%",
    opacity: 0
  }
};`
For element:
`<motion.div 
variants={fooVariants} 
initial="hidden"
animate="visible"
exit="exit">{bar}</motion.div>`
[transitionEnd docs](https://www.framer.com/motion/component/##transform)

**Comment by iamifechi** [comment]
If @YakomazovPavel 's answer doesn't do it for you, try adding the willChange:auto

`<motion.div  variants={fooVariants}  initial="hidden" animate="visible" exit="exit"  style={{willChange:"auto"}}>{bar}</motion.div>`
