### ISSUE TITLE
Can't get shared layout animations to work with Next.js 13

### ISSUE THREAD

**Issue by maurocolella** [framer/motion#1850]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

With Next 13, using separation between server and client components, shared layout animations don't work when implementing the seemingly trivial navigation menu underline. Using either the deprecated or the modern approach (ie. `layoutId` on the target components).

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

This issue could be heavily dependent upon styles and nesting(s). The structure honors HTML and React semantics, but it runs complex animations. Hence: the repro is complete, interactive, commentable and with full source code.

Live:
https://portfolio-2023-git-feature-implement-layout-maurocolella.vercel.app/

Implementation: https://github.com/maurocolella/portfolio_2023/pull/2/files#diff-f7c999b982bfdbf5f3790e5b148e2343ffb7611b9ba579756dabab9fc76cb2e7

**4. Steps to reproduce**

On the example page:
https://portfolio-2023-git-feature-implement-layout-maurocolella.vercel.app/

Simply click navigation items. Transition doesn't take place.

**5. Expected behavior**

I would expect a smooth transition to occur as in the examples.

**6. Video or screenshots**

N/A.

**7. Environment details**

Ubuntu Linux 20.04, Chrome beta, Chrome stable, Firefox.

### Framer Motion won't install

Framer Motion 7+ uses React 18 as a minimum. If you can't upgrade React, install the latest version of Framer Motion 6. 

### `height: "auto"` is jumping

Animating to/from `auto` requires measuring the DOM. There's no perfect way to do this and if you have also applied padding to the same element, these measurements might be wrong.

The recommended solution is to move padding to a child element. See [this issue](https://github.com/framer/motion/issues/368) for the full discussion.

### Type error with `AnimateSharedLayout`

`AnimateSharedLayout` was deprecated in 5.0. Refer to the [upgrade guide](https://www.framer.com/docs/guide-upgrade/##shared-layout-animations) for instructions on how to remove.

### Preact isn't working

Framer Motion isn't compatible with Preact. 

### `AnimatePresence` isn't working

Have all of its immediate children got a unique `key` prop that **remains the same for that component every render**?

```jsx
// Bad: The index could be given to a different component if the order of items changes
<AnimatePresence>
  {items.map((item, index) => <Component key={index} />)}
</AnimatePresence>
```

```jsx 
// Good: The item ID is unique to each component
<AnimatePresence>
  {items.map((item, index) => <Component key={item.id} />)}
</AnimatePresence>
```

Is the `AnimatePresence` correctly outside of the controlling conditional? `AnimatePresence` must be rendered whenever you expect an `exit` animation to run - it can't do so if it's unmounted!

```jsx
// Bad: AnimatePresence is unmounted - exit animations won't run
{isVisible && (
  <AnimatePresence>
    <Component />
  </AnimatePresence>
)}
```

```jsx
// Good: Only the children are unmounted - exit animations will run
<AnimatePresence>
  {isVisible && <Component />}
</AnimatePresence>
```

**Comment by thanhtutzaw** [comment]
yo  I also have this issue in Next js . I solved it for my first time use but , I deleted that animation . Now I want to enable in next js and issue happening .

**Comment by mattgperry** [comment]
Hi there, that source code link isn’t working for me. Please reopen with a sandbox or repo

**Comment by maurocolella** [comment]
@mattgperry was private, sorry.

Here is the sandbox:

https://codesandbox.io/s/hopeful-wozniak-hkf8yx

**Comment by mattgperry** [comment]
That is weird although I think I have them working here https://codesandbox.io/p/sandbox/charming-pine-zz12kx

**Comment by mattgperry** [comment]
When I've got a bit more time I can look into this, there's definietly something different about Next 13

**Comment by maurocolella** [comment]
Thanks a lot @mattgperry . It's early days for this project, and it's going to undergo some changes (maybe Remix, some css tweaks, and I will definitely lose the cheerio parsing once I connect it with a CMS back-end), but I thought I'd raise it as an edge case.

I am not blocked by all means, and if I figure out why it's working this way I'll be happy to share back.

Appreciate the help.

**Comment by MrUltimate** [comment]
Hey folks, I'm running into the same issue here. I'm not sure how to even wrap `AnimatePresence` in NextJs's new App directory because it's throwing all kinds of issues. I'm combining it with `styled-components` and seems like there's some stuff that's happening there too.

Here's how I've currently implemented my `layout.js`:

```
'use client'
import { AnimatePresence } from 'framer-motion'
import { GridOverlay } from '../components/GridOverlay'
import Header from '../components/Header'
import { motion } from 'framer-motion'

import StyledComponentsRegistry from './styles/Registry'
import { dark } from './styles/Theme'
import { ThemeContext } from './styles/ThemeContext'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ThemeContext>
            <AnimatePresence mode="popLayout">
              <GridOverlay />
              <Header />
              {children}
            </AnimatePresence>
          </ThemeContext>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
```

**Comment by Murkrage** [comment]
> That is weird although I think I have them working here https://codesandbox.io/p/sandbox/charming-pine-zz12kx

Your example uses the `pages` directory. @maurocolella uses the new `/app` directory: https://beta.nextjs.org/docs. While still experimental it's definitely the new way of creating Next apps.

There are seemingly a couple of issues with transitions. Most notable: the exit animations do not work (see video). I'm not sure whether the issue is with Framer or with Next. Next does seem to unmount the layout immediately upon navigation. I've tried adding `usePresence` to allow Framer to remove an element after a timeout but even that doesn't work.

https://user-images.githubusercontent.com/6362631/213143210-634ce3fc-49ad-4135-b92a-9b1fe8aaa88d.mov

**Comment by Murkrage** [comment]
Per https://github.com/framer/motion/discussions/1775#discussioncomment-4299578 I have also tried using a `template.tsx` file but that doesn't seem to work either, even though the Next docs specifically mention transitions to be a use-case for it: https://beta.nextjs.org/docs/routing/pages-and-layouts#templates.

**Comment by maurocolella** [comment]
Worth noting that I have organized my client/server components in a
peculiar way to work around apparent bundling issues.

This is related to cheerio as mentioned (which I will drop soon).

That being said, I don't think I am working against either framework, and I
might raise an issue with the Next team for their feedback.

**Comment by dumbravaandrei22** [comment]
I have the same kind of issue in the Next 13.
The Animate Presence is unable to freeze the exiting (children) component.

In the Root Layout, which is a server component, I have this:
![image](https://user-images.githubusercontent.com/14004579/216827827-8ec68fc3-a800-48cb-bf17-935a17794f26.png)

In <Main> (client component) I have this:
![image](https://user-images.githubusercontent.com/14004579/216827862-4b3873c4-872f-42bc-8796-6ae9c1cb7eb4.png)

In <Inner> (client component as well):
![image](https://user-images.githubusercontent.com/14004579/216827926-40751317-5f6e-4fb4-96d3-6c5054f8ffeb.png)

I added <Freeze> as a workaround, but I don't like it.

It seems that both (the new component + the existing one) point somehow to the same component.

**Comment by Murkrage** [comment]
> It seems that both (the new component + the existing one) point somehow to the same component.

This is, presumable, solved using `template.js` (see: https://beta.nextjs.org/docs/routing/pages-and-layouts#templates). From the docs: 
> ...routes that share a template, a new instance of the component is mounted, DOM elements are recreated...

**Comment by jasonkylefrank** [comment]
After reading the Next.js v13 docs regarding the new [Templates feature](https://beta.nextjs.org/docs/routing/pages-and-layouts#templates), I tried it out to house page-transition Framer Motion code.

Unfortunately the exit animation does not work (it's just completely ignored). 

[This](https://github.com/jasonkylefrank/FrontendFYI-YouTube/blob/DRY-transition/2022-11-11-route-transitions-with-next-app-directory/components/page-wrapper.tsx#L29
) is the file that contains my page-transition code.  

Also see my [template.tsx](https://github.com/jasonkylefrank/FrontendFYI-YouTube/blob/DRY-transition/2022-11-11-route-transitions-with-next-app-directory/app/template.tsx) and [layout.tsx](https://github.com/jasonkylefrank/FrontendFYI-YouTube/blob/DRY-transition/2022-11-11-route-transitions-with-next-app-directory/app/layout.tsx) file for more context.

**Comment by jasonkylefrank** [comment]
Another finding:  When using `<AnimatePresence>` in [template.tsx](https://github.com/jasonkylefrank/FrontendFYI-YouTube/blob/DRY-transition/2022-11-11-route-transitions-with-next-app-directory/app/template.tsx), the `onExitComplete()` does not fire.

**Comment by dumbravaandrei22** [comment]
@Murkrage Some time ago I tried to use template.js but it didn't work. i will try again.

@jasonkylefrank For me the exit animation works.
Try to wrap your motion.div into another component (client component).
For that component provide key=pathname as you do.
See my structure here: https://github.com/framer/motion/issues/1850#issuecomment-1418031574

in the inner component please use:
`const [isPresent, safeToRemove] = usePresence();`

Now, the problem is that the old component and the new one are pointing to the same instance (they are the same component):

https://user-images.githubusercontent.com/14004579/217095185-3c52f30b-ce8e-4ac2-9063-dc2b294e8a8f.mov

**Comment by Galanthus** [comment]
I have it working for like 90%. The animation on Exit is or too fast loading animate-in or the exit is is too fast or too slow. The exit and enter works... but still works better using "pages" instead of the new "app" directory.

**layout.tsx:**
```
"use client";

import "@styles/globals.css";

import { anton, roboto } from "lib/fonts";

import { Footer, MainNavigation, MaxWidthWrapper } from "@components/ui";
import { AnalyticsWrapper, DefaultHead } from "@components/shared";
import Newsletter from "@components/sections/Newsletter";
import { AnimatePresence, motion } from "framer-motion";
import { usePathname } from "next/navigation";

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en" className={`${anton.variable} ${roboto.variable}`}>
      <DefaultHead />
      <body className="min-h-screen text-gray-100 bg-midnight">
        <MainNavigation />

        <MaxWidthWrapper type="main">
          <AnimatePresence
            mode="wait"
            initial={false}
            onExitComplete={() => window.scrollTo(0, 0)}
          >
            <motion.div
              key={pathname}
              initial={{ opacity: 0, y: 25 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 25 }}
              transition={{
                type: "spring",
                stiffness: 140,
                damping: 20
              }}
            >
              {children}
            </motion.div>
          </AnimatePresence>
        </MaxWidthWrapper>

        <AnalyticsWrapper />
        <Newsletter />
        <Footer />
      </body>
    </html>
  );
}

```

**Comment by khuezy** [comment]
I got exit animation to work using `appDir` (13.2.2-canary1). `template.tsx` is a lie, so ignore that until they fix it.
What you want to do is in your `layout.tsx` (which is ideally `rsc`), wrap a `Client` component around your `{children}` and have that be wrapped in the `<AnimatePresence>` component.

```typescript
// client.tsx
'use client'
import { motion, AnimatePresence } from 'framer-motion'
import { usePathname } from 'next/navigation'

// Client wraps any client/rsc components with AnimatePresence
export default function Client({children}: { children: ReactNode}) {
  const pathname = usePathname()
  return <AnimatePresence mode='wait' onExitComplete={doYourThing}>
     <motion.div key={pathname}
          initial={{}}
          animate={{}}
          exit={{}}
        >
          {children}
       </motion.div>
   </AnimatePresence >
}
```

```typescript
// layout.tsx
export default function Layout({children}: { children: ReactNode}) {
  return <Client>{children}</Client>
}


```

**Comment by beamercola** [comment]
@khuezy in my instance `pathname` falls into an infinite loop and no route change happens

**Comment by khuezy** [comment]
@beamercola hmm, what does your app structure look like? My solution is a hack until they fix `template.tsx`.

**Comment by khuezy** [comment]
@dumbravaandrei22 I'm using 9.0.3, I'll update to latest and let you know. Although the example above gets exit animations to work, the current problem is that nextjs replaces the contents before the exit animation plays. I believe once `Vercel` fixes `template.tsx`, it will behave correctly.

**Comment by dumbravaandrei22** [comment]
Understood!
Thank you!

**Comment by dumbravaandrei22** [comment]
@khuezy I had tried this: https://github.com/framer/motion/issues/1850#issuecomment-1418031574. Is working, but it seems that the loading UI has a delay.

**Comment by khuezy** [comment]
Ah I see, sorry missed your comment up there. We have the exact same problem.

**Comment by dumbravaandrei22** [comment]
@khuezy Indeed, np. Should we file a new bug to NextJs? 
Or do you track a relevant bug related to this issue on the Vercel side?

**Comment by khuezy** [comment]
I haven't found a related ticket on the nextjs repo. Maybe we can create w/ some a minimal repro?

**Comment by akashlama1998-icloud** [comment]
It does work but you have to be a bit creative with it. Here's my solution.

1. First, create a client component which will be the wrapper for Framer Motion's AnimatePresence.

```tsx
// LayoutAnimatePresence.tsx

'use client'

import { AnimatePresence } from 'framer-motion'
import { usePathname } from 'next/navigation'
import { Fragment, type PropsWithChildren } from 'react'

export default function LayoutAnimatePresence({ children }: PropsWithChildren) {
  const pathname = usePathname()

  return (
    <AnimatePresence initial={false} mode="wait">
      <Fragment key={pathname}>{children}</Fragment>
    </AnimatePresence>
  )
}
```
2. Then, use it in your root layout.

```tsx
// layout.tsx

import type { PropsWithChildren } from "react"

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
          <LayoutAnimatePresence>{children}</LayoutAnimatePresence>
      </body>
    </html>
  )
}
```

**Comment by akashlama1998-icloud** [comment]
It **does** work but you have to be a bit creative with it. Here's my solution.

1. First, create a client component which will be the wrapper for Framer Motion's [AnimatePresence](https://www.framer.com/motion/animate-presence/).

```tsx
// LayoutAnimatePresence.tsx

'use client'

import { AnimatePresence } from 'framer-motion'
import { usePathname } from 'next/navigation'
import { Fragment, type PropsWithChildren } from 'react'

export default function LayoutAnimatePresence({ children }: PropsWithChildren) {
  const pathname = usePathname()

  return (
    <AnimatePresence initial={false} mode="wait">
      <Fragment key={pathname}>{children}</Fragment>
    </AnimatePresence>
  )
}
```
2. Then, use it in your root layout.

```tsx
// layout.tsx

import type { PropsWithChildren } from "react"

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
          <LayoutAnimatePresence>{children}</LayoutAnimatePresence>
      </body>
    </html>
  )
}
```

**Comment by dumbravaandrei22** [comment]
@akashlama1998-icloud is the mode=wait required?

**Comment by NacereddineRebouh** [comment]
@akashlama1998-icloud I tried your solution, and it works only in the **page directory.**

**Comment by akashlama1998-icloud** [comment]
@dumbravaandrei22 Updated code for LayoutAnimatePresence wrapper component for Next.js 13.

```tsx
// LayoutAnimatePresence.tsx

'use client'

import { AnimatePresence, AnimatePresenceProps } from 'framer-motion'
import { usePathname } from 'next/navigation'
import { Fragment, type PropsWithChildren } from 'react'

export default function LayoutAnimatePresence({
	children,
	...restProps
}: PropsWithChildren<AnimatePresenceProps>) {
	const pathname = usePathname()

	return (
		<AnimatePresence {...restProps}>
			<Fragment key={pathname}>{children}</Fragment>
		</AnimatePresence>
	)
}
```

**Comment by akashlama1998-icloud** [comment]
@NacereddineRebouh You're right! I was about to post this it seems like exit animations still doesn't work inside the new app directory. May be any update by @mattgperry

**Comment by NacereddineRebouh** [comment]
@akashlama1998-icloud a few minutes ago, I had the onExitAnimation fire, and the pages console log when unmounting, but still, the exit animation does not work; I even tried using template.tsx.
something weird is happening with nextjs.
I had two pages: /page1 and /page2
-each one with a use effect that console log a message when mounting and unmounting
-I used your LayoutAnimatePresence in Layout.tsx,
-and I had a Header with Two Link tags to page1 and page2
here's what I had in the console:
**_page 1 mounted_**
**_LayoutAnimatePresence  mounted_**
navigating to Page2.......
**_page 1 unmounting_**
**_page 2 mounted_**

everything works as expected but the exitAnimation.

**Comment by akashlama1998-icloud** [comment]
@NacereddineRebouh Yes the same thing is happening with me.. till the bug is reviewed and fixed I shifted my whole project to the old way using pages directory.. @mattgperry is the only faith and hope I have now.. 🥲

**Comment by ShueiYang** [comment]
I also give a try on the new app folder and indeed I have trouble with the exit animation, it just don't work in the new App even with the template.js and separate it as a client component,  however, in the pages folder it works fine.

**Comment by atabv** [comment]
Wow, four months in and still not a fix. Next.js devs are sleeping.

**Comment by Pipoteex** [comment]
Hi i have the same problem in Next 13. The exit animation not work if the AnimatePresence component is in the layout root component

**Comment by willhindson** [comment]
+1 same problem, would love to see a fix for exit animations, tried on latest Next canary release (13.3.2-canary.6) and still not working

**Comment by Dimitri-Jacquin** [comment]
also can't get it to work, it's a shame because the latest version of Next.js is very easy to use

**Comment by willhindson** [comment]
Not sure if it's a Framer motion or Next issue at this point though 😅

**Comment by jamesvclements** [comment]
Any updates on this, or is there an issue in the Next.js repo we can follow for when template.tsx will support it?

**Comment by jamesvclements** [comment]
Any updates on this? In the latest versions of framer motion `10.12.4`and next `13.3.2-canary.12`, the `exit` animation is working, but the premature navigation that @khuezy mentioned is still happening, which causes a weird flash of the next page's content before the animation's trigger:

https://share.cleanshot.com/KmksdBxN

That being said I'm still using `layout.tsx`. If switching to `template.tsx`, do we lose all the benefits of SSR? Or will the `page.tsx` still be SSR'd, and only the root layout misses that?

**Comment by alainkaiser** [comment]
Any updates on this from anyone? Would be helpful...

**Comment by nohr** [comment]
It looks like the appDir is stable as of 13.4 today. Looking forward to getting a fix on this soon

**Comment by SchmidtDavid** [comment]
Is there also an issue for this open somewhere on Nextjs's repo or is this suposed to stay on the framer repo?

**Comment by maurocolella** [comment]
@SchmidtDavid I am sorry I didn't follow up with Next.js/Vercel in part because the app directory was in rapid flux/beta at that time. There were several known instabilities and [incompatibilities](https://github.com/vercel/next.js/issues/42530) with the wider React ecosystem.

I was hoping that the framer motion team (@mattgperry ) would have more direct channels & the bandwidth to look into it.

That said, given the traction this has gained, and that the app directory is emerging/has emerged from beta, I am more than happy to follow up.

**Comment by maurocolella** [comment]
Here. I have filed a [bug with Next.js](https://github.com/vercel/next.js/issues/49279).

In the meantime, for some of these scenarios, a possible workaround is to simply use CSS transitions, or the gorgeous [view transitions](https://www.patterns.dev/posts/view-transitions) now available in Chrome.

**Comment by Dimitri-Jacquin** [comment]
Thank you maurocolella for this great idea, could you please provide more details about your proposal? Like adding CSS classes with effects is that your idea? And why does the patterns-view transitions  doesn't work in all browsers? How to use it with next?

**Comment by maurocolella** [comment]
@Dimitri-Jacquin all the effects that can be achieved using Framer Motion build up on underlying APIs, like CSS transitions yes or CSS animations, or the [Web Animations API](https://www.smashingmagazine.com/2021/09/orchestrating-complexity-web-animations-api/).

So any of these solutions can be used to work around the temporary misalignment between Framer Motion and Next.js. I am sure you can find tutorials for any of them easily for quite a large number of effects.

As for view transitions, it's a relatively new API in the exploratory stages. It has [yet to become a standard](https://github.com/WICG/view-transitions), but it's on the way. The article I linked has details about how to use it with Next.js. Just scroll down [under the React section](https://www.patterns.dev/posts/view-transitions#react-component-example), although you can find [other great tutorials for that](https://javascript.plainenglish.io/page-transitions-in-reactjs-with-react-router-v6-and-the-built-in-view-transitions-api-no-73ab52c6fd7b) as well.

**Comment by Dimitri-Jacquin** [comment]
Has anyone tried it with spring-react?

**Comment by alainkaiser** [comment]
Guys, some updates from my side and a small overview of what it looks like on my end:

My setup:
- "next": "^13.4.1"
- "framer-motion": "^10.12.10"

My "PageTransition" component:

```
'use client'

import {AnimatePresence, motion} from 'framer-motion'
import {usePathname} from 'next/navigation'

interface Props {
  children: React.ReactNode
}

function PageTransition({children}: Props) {
  const pathname = usePathname()

  return (
    <AnimatePresence initial={false} mode='wait'>
      <motion.div key={pathname} variants={variants} initial='in' animate='inactive' exit='out'>
        {children}
      </motion.div>
    </AnimatePresence>
  )
}

const variants = {
  inactive: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 1,
      ease: 'easeInOut',
    },
  },
  out: {
    opacity: 0,
    y: -100,
    transition: {
      duration: 1,
      ease: 'easeInOut',
    },
  },
  in: {
    y: 100,
    opacity: 0,
    transition: {
      duration: 1,
      ease: 'easeInOut',
    },
  },
}

export default PageTransition
```


My WebLayout component in which the PageTransition component is used (layout.tsx):

```
'use client'

import {Provider as WrapBalancerProvider} from 'react-wrap-balancer'
import Footer from '../../components/layout/footer'
import HeaderBar from '../../components/layout/header-bar'
import PageTransition from '../../components/misc/page-transition'
import './../../styles/globals.css'
import TailwindIndicator from '../../components/misc/tailwind-indicator'

export default function WebLayout({children}: {children: React.ReactNode}) {
  return (
    <>
      <div className='flex flex-col screen-height'>
        <WrapBalancerProvider>
          <HeaderBar />
          <PageTransition>
            <main className='flex-1'>{children}</main>
          </PageTransition>
          <Footer />
        </WrapBalancerProvider>
      </div>
      <TailwindIndicator />
    </>
  )
}
```

The current behaviour:

https://github.com/framer/motion/assets/18368657/39392c79-c0f9-4450-a96a-65c7130103de

What exactly am I doing wrong? I have already tried a few things, but I can't find the right information anywhere. Would greatly appreciate help.

**Comment by jamesvclements** [comment]
@alainkaiser it's seeming like this is an issue on the Next.js side that will need to be fixed:
https://github.com/vercel/next.js/issues/49279

**Comment by saurabhsri108** [comment]
I was using old architecture of pages in Next-13.4. This article helped me solved it: https://blog.logrocket.com/advanced-page-transitions-next-js-framer-motion/#adding-animatepresence

The issue was adding key={router.pathname} in the _app.tsx and it worked.

```tsx
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Inter } from "next/font/google";
import Head from "next/head";
import Header from "@/containers/Header";
import Footer from "@/containers/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import Script from "next/script";
import { AnimatePresence, motion } from "framer-motion";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

const variants = {
  initialState: { opacity: 0 },
  animateState: { opacity: 1 },
  exitState: { opacity: 0 }
};

export default function App({ Component, pageProps, router }: AppProps) {
  return (
    <>
      <Head>
        <title>NextJS 13 | Learn NextJS 13 with old architecture</title>
        <meta
          name="description"
          content="Learn NextJS 13 pages directory architecture"
        />
      </Head>

      {/*<Partytown debug={true} forward={["dataLayer.push"]} />*/}
      <Script id="partytown-gtm" strategy="afterInteractive" dangerouslySetInnerHTML={{
        __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','XXX');`
      }} />
      <ClerkProvider {...pageProps}>
        <Header />
        <AnimatePresence initial={false} mode="wait">
          <motion.main
            initial="initialState"
            animate="animateState"
            exit="exitState"
            transition={{
              duration: 0.2
            }}
            variants={variants}
            key={router.pathname}
            className={`${inter.variable} font-inter`}>
            <Component {...pageProps} />
          </motion.main>
        </AnimatePresence>
        <Footer />
      </ClerkProvider>
    </>
  );
}
```

**Comment by IntiSilva** [comment]
Having the same problem with the new app directory, a thing I noticed is that it's exclusively the exit animation bc I also have the "initial" prop set to false in AnimatePresence and that works hahaha

`export default function RootLayout({children }) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <AnimatePresence type='wait' initial={false}>
        {children}
        </AnimatePresence>
      </body>
    </html>
  )
}`

**Comment by AksRK** [comment]
Guys, I apologize in advance if I duplicate the question.
On next 13, the exit animation works, only children is replaced with a new one and it turns out that there are 2 new pages on the screen at the same time. Is this a problem on the next side? Or am I doing something wrong?

Main
`
<LazyMotion features={domAnimation}>
  <AnimatePresence initial={false} mode={'popLayout'}>
    <m.div
	    style={{y: 0}}
	    key={pathName}
	    className={styles.main}
	    initial="initial"
	    animate="animate"
	    exit="exit"
	    variants={variants}
    >
	    {children}
    </m.div>
  </AnimatePresence>
</LazyMotion>
`

layout

`
export default function RootLayout({children,}: { children: ReactNode }) {
  
  return (
      <html lang="en">
      <body className={inter.className}>
        <Main>
          {children}
        </Main>
      </body>
      </html>
  )
}
`

**Comment by GentikSolm** [comment]
Ive made some progress on this. I still cannot get exit animations to work, but this snippet works well for enter animations that are pretty smooth. The only problem is that these dont load when the server is initial SSRing the page. after its cached it works fine. In the video, the documents page SSR's on the first click, then after that you get decently smooth transitions.
```tsx
// app/template.tsx
'use client';

import clsx from 'clsx';
import { useEffect, useState } from 'react';

export default function Template({ children }: { children: React.ReactNode }) {
  const [fade, setFade] = useState(false);
  useEffect(() => {
    setFade(true);
    return () => {
      setFade(false);
    };
  }, []);
  console.log(fade);
  return (
    <div
      className={clsx(
        fade ? 'translate-y-0 opacity-100' : 'translate-y-3 opacity-0',
        'transition duration-500 ease-out',
      )}
    >
      {children}
    </div>
  );
}
```
https://github.com/framer/motion/assets/34988548/f18dec5d-ec75-40f5-8738-892349efb3a2

**Comment by AksRK** [comment]
It turned out to start the animation of entry and exit. Maybe someone will be useful 😅

https://github.com/AksRK/next13-page-transition

**Comment by GentikSolm** [comment]
> Framer motion devs dont want to fix this? like, its been months now

This is a direct issue with next, and not framer, once [this](https://github.com/vercel/next.js/issues/49279#issuecomment-1541939624) issue is resolved, it should work as indeed.

**Comment by vikyw89** [comment]
still doesn't work

**Comment by 4zad** [comment]
> still doesn't work

I can second this 😭 

That being said I was able to get it working without an exit animation by using the motion tag as the root tag on each page (i.e., home, about, contact) and not using mode='wait' with AnimatePresence.

**Comment by Dimitri-Jacquin** [comment]
Inter sport

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Muhammad Ahmed ***@***.***>
Envoyé : Wednesday, July 19, 2023 3:02:36 AM
À : framer/motion ***@***.***>
Cc : DIMITRI JACQUIN ***@***.***>; Mention ***@***.***>
Objet : Re: [framer/motion] Can't get shared layout animations to work with Next.js 13 (Issue #1850)


still doesn't work

I can second this 😭

That being said I was able to get it working without an exit animation by using the motion tag as the root tag on each page (i.e., home, about, contact) and not using mode='wait' with AnimatePresence.

**Comment by ShueiYang** [comment]
@4zad  I am doing the same thing for the enter animation, still can't figure it out for exit animation.

**Comment by minhduc8a2** [comment]
Thank you @khuezy 
It's working well

**Comment by nmitic** [comment]
> If someone could provide a link with example of native implementation with just CSS I would be grateful. Also is there a way to achieve this with just plain JS? Like some kind of hooks, which would allow me to use gsap or any other animation library?
> 
> @maurocolella I've seen you stating that finding those examples of effects in just CSS is easy, but to be honest, all I could find was Framer Motion staff :D Seems like a standard in React community (coming from Vue.js background).

In order to do native JS css anim we need routing guards which has been removed or planned to come in the app dir. 

Also, even without framer you would still need to hack things around. 

I honestly prefer to wait for issue to be fixed on next js.

**Comment by maurocolella** [comment]
@pzpsofficial I will turn off notifications for this thread after this reply, as I receive my fair share of notifications and cannot keep up with everything, but the actual standards of internet and front-end dev should always be CSS, HTML and ECMAscript first. By that I mean: it's critical to have a good grasp on them, and frameworks are just sugar coating.

That said, people do rely on Framer Motion because it abstracts these away, and simplifies the task of translating a visual effect into CSS/JavaScript under the hood, but it's really (almost) all that it does.

Does it very nicely, but still.

Whether using Vue or Next or any other framework, any effect you see can be accomplished using web standards.

Here using pure CSS. It is not optimal, but it is pure CSS:
https://codepen.io/rm/pen/AXpmja

Here is another example that uses more elegant coding techniques along with a step-by-step breakdown:
https://vitaliy-kirenkov.medium.com/sliding-underline-in-navigation-b95399fc4601

Also, visual effects like this do not and should not depend on routing, but on user interaction (so you could trigger them independently on separate events as well, like mouseenter/mouseleave).

Effects are a styling concern, independently from routing, navigation, or content. Either should be able to work without the other.

Finally, I found this by searching for "sliding underline nav" on Google - Google is adaptive, returns results based on what you were searching before. Hence: keep it simple.

Back to basics works.

**Comment by pzpsofficial** [comment]
Thanks for reply, I think there was a misunderstanding as I had page transitions in mind the whole time.

In cases like this simple underline the basics are even more than enough ;)

Kind regards,
Bartek

**Comment by su-pull** [comment]
For now, I made an exit motion using RSC.
https://github.com/su-pull/rsc-link-motion

**Comment by Gaurav4604** [comment]
Hi everyone,
[I followed this thread and came across a hacky solution, It seems to work well for me](https://github.com/vercel/next.js/issues/49279#issuecomment-1718177583)

Check it out, might be useful.

using 
- nextJS (v 13.4.19)
- framer-motion (v 10.16.4)

The thread itself has a working example, but I've implemented a solution with much less code as well.

[My working example](https://newsletter-sign-up-tau-jet.vercel.app)

[Repo link](https://github.com/Gaurav4604/React-Showcase/tree/master/Junior/newsletter-sign-up)

[This is the FrozenRouter implementation that makes exit animations possible](https://github.com/Gaurav4604/React-Showcase/blob/master/Junior/newsletter-sign-up/src/components/FrozenRouter.tsx)

[Here is where the FrozenRouter component is being used](https://github.com/Gaurav4604/React-Showcase/blob/master/Junior/newsletter-sign-up/src/app/client.tsx)


I hope this is helpful to all facing this issue.

**Comment by joshdavenport** [comment]
Feels like [npostulart is right in their asessment that this feels hacky](https://github.com/vercel/next.js/issues/49279#issuecomment-1719966142) but it does seem to work pretty well. Has anybody tried this in the wild and found any weirdness or conversely that it just works with no real issue?

**Comment by Gaurav4604** [comment]
@joshdavenport I’ve added a personal example to my comment, where I’ve used it for a page transition itself, it does seem to work perfectly fine.

**Comment by joshdavenport** [comment]
Indeed @Gaurav4604, it's your example that triggered the question, seeing more people use the technique I mean. I'm wondering if anybody has managed to try this in prod in an app with many moving parts, complex routing, complex state, etc.

**Comment by Gaurav4604** [comment]
Ah ok, that makes sense, I'll let you know if I do so myself as well. Does seem to get the job done for time-being.

**Comment by cdebotton** [comment]
> Indeed @Gaurav4604, it's your example that triggered me wondering about it - seeing more people use the technique I mean. I'm wondering if anybody has managed to try this in prod in an app with many moving parts, complex routing, complex state, etc.

The biggest concern is more so that the technique uses code that isn’t publicly exported from nextjs, which would mean it’s not intended for anything but internal use. A minor or patch update could break this functionality without notice under semver.

**Comment by cdebotton** [comment]
Just a follow up, I'm trying this approach in Next 13.5 which just came out today and I'm finding that the any components underneath a Frozen Router won't update via HMR which makes it pretty much unusable.

**Comment by Gaurav4604** [comment]
> Just a follow up, I'm trying this approach in Next 13.5 which just came out today and I'm finding that the any components underneath a Frozen Router won't update via HMR which makes it pretty much unusable.

@cdebotton I just updated my import for frozenRouter for it to work with AnimatePresence on nextJS 13.5.1,
[You can find it here](https://github.com/Gaurav4604/React-Showcase/blob/next13.5.1/Junior/newsletter-sign-up/src/components/FrozenRouter.tsx)
but I get it, this needs a much more permanent fix, since these are not publicly exported components from nextJS.

**Comment by joshdavenport** [comment]
> Just a follow up, I'm trying this approach in Next 13.5 which just came out today and I'm finding that the any components underneath a Frozen Router won't update via HMR which makes it pretty much unusable.

Ouch. Yes, this is a deal breaker. I guess not too bad if you're only working on something small but for anything else this makes drastically slows down development.

Seems like we're in a kind of limbo with this, framer obviously can't change what Next is doing, and the Next team don't seem massively motivated to move on this (https://github.com/vercel/next.js/issues/49279) which is a shame but somewhat understandable as they do have more demanding priorities I'm sure.

**Comment by baptistebriel** [comment]
Hi there! Whereas [this solution](https://github.com/vercel/next.js/issues/49279#issuecomment-1675393849) worked fine for me to get page transitions to work with Next.js 13, I am getting the following error from Framer Motion's AnimatePresence & PopChildMeasure. Any fixes existing to avoid this error? The lifecycle of animations is working fine, just the error is being thrown.

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `PopChild`.
```

**Comment by Frumba** [comment]
@baptistebriel Check the new version of the Child with the forwardRef here https://github.com/npostulart/nextgram-with-page-transitions/blob/main/src/app/ClientLayout.tsx#L12 😄

**Comment by Gaurav4604** [comment]
> Hi there! Whereas [this solution](https://github.com/vercel/next.js/issues/49279#issuecomment-1675393849) worked fine for me to get page transitions to work with Next.js 13, I am getting the following error from Framer Motion's AnimatePresence & PopChildMeasure. Any fixes existing to avoid this error? The lifecycle of animations is working fine, just the error is being thrown.
> 
> ```
> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
> 
> Check the render method of `PopChild`.
> ```

[Take a look at the docs for the same](https://www.framer.com/motion/animate-presence/###mode)
It mentions that if you're to use a **custom component** as a child of _AnimatePresence_ with "popLayout", you need to pass a ref accordingly, so as to let framer motion track the component.

**Comment by baptistebriel** [comment]
Thank you @Frumba and @Gaurav4604 — that worked, thank you for the quick reply.

**Comment by su-pull** [comment]
Hello.
I haven't seen it for a while, but has the exit motion is working?

**Comment by wangwailok** [comment]
> Hello. I haven't seen it for a while, but has the exit motion is working?

just tried with 13.5.3 and  "framer-motion": "^10.16.4",
still not working

**Comment by devchitect** [comment]
Actually i got an idea and it quite a bit not a hacky solution,
Instead of using exit animation, because next router and ssr works different than react.
I use 2 enter animation, this requires router.push() instead of using href in <Link/> component. 

1 for exit, i use setTimeOut() to create a delay before it actually changes in url, 
before url change, i change state which display an component for exit only.

and when the url changed, i use useEffect to change the state again to hide that exit component. 
then the default enter animation come to work.

**Comment by devchitect** [comment]
Actually i got an idea and it quite a bit not a hacky solution,
Instead of using exit animation, because next router and ssr works different than react.
I use 2 enter animation, this requires router.push() instead of using href in component.

1 for exit, i use setTimeOut() to create a delay before it actually changes in url,
before url change, i change state which display an component for exit only.

and when the url changed, i use useEffect to change the state again to hide that exit component.
then the default enter animation come to work.

Kinda looks like this:

`
export default function PageWrapper({children} : {children: React.ReactNode}){

    const path = usePathname();
    const dispatch = useDispatch();
    const transitionValue = useSelector((state : RootState) => state.transition.type)

    useEffect(() => {
        dispatch(transition('enter'));
    },[dispatch,path])

    return (
       <>
            <div>
                {transitionValue === 'exit' && <ExitAnimation/>}

                <motion.div
                key={path}
                style={{background: "#000000"}}
                className='fixed top-full right-0 left-0 w-screen h-screen z-30 '
                variants={slidedown}
                initial='initial'
                animate='animate'
                transition={{delay: 0, duration: 1, ease: 'easeInOut'}}
                />
               
                {children}
                {/* <ScrollTrigger/> */}
            </div>
        </>
    )
}
`

**Comment by devchitect** [comment]
Actually i got an idea and it quite a bit not a hacky solution,
Instead of using exit animation, because next router and ssr works different than react.
I use 2 enter animation, this requires router.push() instead of using href in component.

1 for exit, i use setTimeOut() to create a delay before it actually changes in url,
before url change, i change state which display an component for exit only.

and when the url changed, i use useEffect to change the state again to hide that exit component.
then the default enter animation come to work.

- trigger exit:

`  const navigate = (currpath : string) => {
        const navigateDelay = 1000;
        dispatch(transition('exit'));
        setTimeout(()=>{
            router.push(currpath, { scroll: false });        
        }, navigateDelay)
    }`

- hide exit, trigger enter:

` useEffect(() => {
        dispatch(transition('enter'));
    },[dispatch,path])

    return (
       <>
            <div>
                {transitionValue === 'exit' && <ExitAnimation/>}

                <motion.div
                key={path}
                style={{background: "#000000"}}
                className='fixed top-full right-0 left-0 w-screen h-screen z-30 '
                variants={slidedown}
                initial='initial'
                animate='animate'
                transition={{delay: 0, duration: 1, ease: 'easeInOut'}}
                />
               
                {children}
                {/* <ScrollTrigger/> */}
            </div>
        </>
    )`

**Comment by evankirkiles** [comment]
Here's my experimental branch of next.js that enables exit transitions with `AnimatePresence` by adding in a custom `Glue` component (supplied in a `glue.tsx`) where we _can_ monitor the lifecycle of routes:

Draft PR: https://github.com/vercel/next.js/pull/56591
Discussion: https://github.com/vercel/next.js/discussions/56594

The final solution in `next.js` is going to have to inevitably be something of this sort, as this enables route transitions even within parallel routes (where you can't rely on `pathname` or global navigation events to perform the transitions).

**Comment by su-pull** [comment]
@devchitect
I think so too this not a hack, was tested v0.  [#f788d84](https://github.com/su-pull/react-navigate-motion/commit/f788d84e87c31551be1f4430a9c9d7342da38203)

After all, the actual purpose of Exit animation is to stop the transition of the a tag.
react-router and Next.js Link component is use internally to transition pages programmatically ```e.preventDefault()```.
The framework actually extends the a tag for usability.

This is not a problem on the Next.js (RSC) side.
It's an implementation issue on the routing system and library side.

**Comment by MrUltimate** [comment]
Has anyone tried this with NextJS 14?

**Comment by rfros** [comment]
> Has anyone tried this with NextJS 14?

yes -- issue still present in `14.0.4`; am hopeful draft PR from @evankirkiles gets some eyeballs on it... seems to have gone somewhat stale, though 😞 https://github.com/vercel/next.js/pull/56591

**Comment by mattgperry** [comment]
Closing here as framework-specific integrations isn't something I'm going to concentrate on this year.

**Comment by mattgperry** [comment]
So as an update I was hacking around with this the last couple days to see if anything could be done here. Basically, not really?

My first approach was just to see if I could use existing APIs and as plenty of people before me have found out, the way App Router works just doesn't offer the hooks that we'd need to do this right.

With the [<ViewTransitions />](https://react.dev/reference/react/ViewTransition) component coming in React itself I thought this might be a nice time to build something on that. My conclusion here is I will *probably* still make an API so you can use this without the gross CSS psuedo element syntax — but we'll see.

I'm working with a very straightforward setup where I have a gallery list view, that opens into full screen, then when we want prev/next buttons that the images go left and right. I've bumped into a few problems that you'd expect to work. For instance an overlay that contains an image shared between the list view and the full screen view - the overlay is always drawn on top of the image it contains (???). Or the next/right buttons - problem is if the ViewTransition doesn't have a matching pair, but it also isn't the root unmounting element, then its enter/exit animations don't run. It seems completely impossible to set it up this way in Next.js, even with layouts I find these are remounting on every page navigation.

Perhaps for more straightforward examples this kind of API would be useful? Or as a limited alpha perhaps
