### ISSUE TITLE
[BUG] exit animation not being triggerd

### ISSUE THREAD

**Issue by oshalom-dcg** [framer/motion#998]
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I'm recreating a dropdown from facebook's new UI. Noticed that the exit animation isn't firing when navigating between the two panels. This could be a coding issue on my end, very new to animation mechanics 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/loving-nobel-p5m0t?file=/src/FacebookDropdown.jsx

**4. Steps to reproduce**

1. Head over to the sandbox enviorment
2. Click on toggle
3. Click on any number, this will trigger a animation of the 2nd panel which is correct but the first panel's exit animation isn't triggered. 

**5. Expected behavior**

When clicking on any of the numbers, the first panel should translateX -400 pixels instead of just disappearing. 

**6. Video or screenshots**

If applicable, add a video or screenshots to help explain the bug.

**7. Environment details**

Mac Mojave, latest Chrome

**Comment by mattgperry** [comment]
This is addressed in the ticket FAQs

**Comment by oshalom-dcg** [comment]
hi @mattgperry  ty for the reply! can you help me understand which faq addresses this?
my components are unmounting like so:
```jsx
                 {isFirstPanel && (
                    <FirstPanel
                      layout
                      layoutId="first"
                      initial={{
                        x: -400
                      }}
                      animate={{
                        x: 0
                      }}
                      exit={{
                        x: -400
                      }}
                      transition={{
                        type: "tween"
                      }}
                    >
                    </FirstPanel>
                  )}
                  {!isFirstPanel && (
                    <SecondPanel
                      layout
                      layoutId="second"
                      initial={{
                        x: 400
                      }}
                      animate={{
                        x: 0
                      }}
                      exit={{
                        x: 400
                      }}
                      transition={{
                        type: "tween"
                      }}
                    >
                    </SecondPanel>
                  )}
                  ```

**Comment by mattgperry** [comment]
Sure - the unmounting components need to be direct children of AnimatePresence

**Comment by oshalom-dcg** [comment]
@mattgperry i made an update to the sandbox https://codesandbox.io/s/loving-nobel-p5m0t?file=/src/FacebookDropdown.jsx

<img width="432" alt="Screen Shot 2021-02-22 at 11 25 00 AM" src="https://user-images.githubusercontent.com/70663071/108745378-9d091500-7500-11eb-97e5-a6ebcc306ad5.png">

They are now direct children but the exit animation still isn't firing, any thoughts on why that could be?

**Comment by mattgperry** [comment]
Oh is open not becoming false at the same time?

**Comment by oshalom-dcg** [comment]
correct, open is not becoming false at the same time. open just shows the hoverable dropdown, whereas the `isFirstPanel` gets toggled to `true` and `false` and should trigger the exit animations

**Comment by mattgperry** [comment]
Thanks for clarification! I misread that to begin with, apologises

**Comment by mattgperry** [comment]
Ah I see. Ok this was actually the other one in the FAQs 😅. Neither child has a unique `key`. So `AnimatePresence` sees them as the same. So no exit animation is fired.

Additionally what you'll see is that if you just add keys, the two items stack while one leaves and the other enters. We don't currently "pop" the exiting one from the layout, so you can add `<AnimatePresence exitBeforeEnter />` to make sure one leaves before the new one enters.

**Comment by oshalom-dcg** [comment]
omg that fixed it! thought key applied only when using arrays, thank you so much!
